config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  devise_for :users

  resources :lists do
  resources :items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = @list.items
  end

  def show
  end

  def new
    @item = @list.items.new
    render partial: "form"
  end

  def create
    @item = @list.items.new(item_params)

    if @item.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to list_path(@list)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to list_path(@list)
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = current_user.lists.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_with(model: [@list, @item], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.number_field :price, placeholder: "$" %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
# <h1> Edit Item </h1>
# <%= form_with(model: @item, local:true) do |f| %>
#   <div class="field">
#   <%= f.label :name %>
#   <%= f.text_field :name, required: true, placeholder: "Name" %>
#   </div>
#   <div class="field">
#   <%= f.label :price %>
#   <%= f.number_field :price, placeholder: "$" %>
#   </div>
#   <%= f.submit %>
#   <% end %>

app/views/items/index.html.erb
    <h3> All Items </h3>
      <ul>
        <% @items.each do |item| %>
          <li>
            <%= item.name %>
          </li>
          <%= link_to "View Item", list_item_path(@list, item) %>
          <%= link_to "Edit Item", edit_list_item_path(@list, item) %>
          <%= link_to "Delete Item", list_path(@list, item), method: :delete %>
        <% end %>
      </ul>
  <hr />
<%= link_to "Add Item", new_list_item_path %>

app/views/items/new.html.erb
# <h1> Add Item </h1>
# <%= form_with(model: @item, local:true) do |f| %>
#   <div class="field">
#   <%= f.label :name %>
#   <%= f.text_field :name, required: true, placeholder: "Name" %>
#   </div>
#   <div class="field">
#   <%= f.label :price %>
#   <%= f.number_field :price, placeholder: "$" %>
#   </div>
#   <%= f.submit %>
#   <% end %>

app/views/layouts/_navbar.html.erb
<nav class="green dark-2">
  <div class="nav-wrapper">
      <a href="#" class="brand-logo"> Shopping List </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">

  <% if current_user %>

    <li>
    <%= link_to "Lists", lists_path %>
    </li>
    <li>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </li>

  <% else %>

    <li>
    <%= link_to "Login", new_user_session_path %>
    </li><li>
    <%= link_to "Register", new_user_registration_path %>
    </li>

  <% end %>

  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1> Edit List </h1>
<%= form_with(model: @list, local:true) do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
  <% end %>

app/views/lists/index.html.erb
<h2> Welcome <%= current_user.first_name %> </h2>
  <hr />
    <h3> Your Shopping Lists </h3>
      <ul>
        <% @lists.each do |list| %>
          <li>
            <%= list.name %>
          </li>
            <%= link_to "View List", list_path(list) %>
            <%= link_to "Edit List", edit_list_path(list) %>
            <%= link_to "Delete List", list_path(list), method: :delete %>
        <% end %>
      </ul>
  <hr />
<%= link_to "Add List", new_list_path %>

app/views/lists/new.html.erb
<h1> Add List </h1>
<%= form_with(model: @list, local:true) do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
  <% end %>

app/views/lists/show.html.erb
<h3> <%= @list.name %> </h3>
<hr />
  <h5> Items: </h5>
    <ul>
      <% @list.items.each do |item| %>
       <li>
        <%= item.name %> - $<%= item.price %>
       </li>
       <%= link_to "Edit Item", edit_list_item_path(@list,item) %>
       <%= link_to "Delete Item", list_item_path(@list, item), method: :delete %>
        <% end %>
    </ul>
  <hr />
<%= link_to "New Item", new_list_item_path(@list) %>
<%= link_to "Back", lists_path %>